language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/BasicUsage/BasicUsage.ino
    - PLATFORMIO_CI_SRC=examples/LedBlink/LedBlink.ino

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio ci --lib="." --board=esp32doit-devkit-v1